version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gopay-woocommerce-integration
        volumes:
            - ./admin:/usr/src/myapp/admin
            - ./includes:/usr/src/myapp/includes
            - ./languages:/usr/src/myapp/languages
            - ./check_requirements.php:/usr/src/myapp/check_requirements.php
            - ./composer.json:/usr/src/myapp/composer.json
            - ./composer.lock:/usr/src/myapp/composer.lock
            - ./index.php:/usr/src/myapp/index.php
            - ./uninstall.php:/usr/src/myapp/uninstall.php
            - ./woocommerce-gopay.php:/usr/src/myapp/woocommerce-gopay.php
        tty: true
