name: Create release

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Package plugin
        run: |
          mkdir -p gopay-gateway
          rsync -av --exclude='gopay-gateway' \
                    --exclude='.git*' \
                    --exclude='.github' \
                    --exclude='composer.json' \
                    --exclude='composer.lock' \
                    . gopay-gateway/
          zip -r gopay-gateway-${{ github.ref_name }}.zip gopay-gateway

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: gopay-gateway-${{ github.ref_name }}.zip
          prerelease: true
